language: bash
sudo: required
services: [docker]
after_success:
- openssl aes-256-cbc -K <travis-key> -iv <travis-iv>
    -in .snapcraft/travis_snapcraft.cfg
    -out .snapcraft/snapcraft.cfg -d
deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v $(pwd):$(pwd) -t ros:kinetic-robot sh -c
        "apt update -qq && apt install libglfw3-dev libusb-1.0-0 build-essential libgtk-3-dev snapcraft -y && cd $(pwd) &&
        snapcraft && snapcraft push *.snap --release edge"
    on:
      branch: master


# how to get the librealsense stuff into snapcraft yaml? shouldnt be dockers problem 