language: bash
sudo: required
services: [docker]
after_success:
- openssl aes-256-cbc -K $encrypted_893a7fde9e81_key -iv $encrypted_893a7fde9e81_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d

jobs:
  include:
    - stage: Build Snap
      script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c
              "apt update -qq &&
               cd $(pwd) &&
               ./generate_snap.sh"
      skip_cleanup: true
    - stage: Release Snap
      script:  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] ; then 
                 snapcraft push snap_ws/*.snap --release edge;
               fi
      skip_cleanup: true
