name: ros-realsense-d400
version: '0.1.2'
summary: Realsense Camera D400 modified ros driver and realsense SDK Snap.
description: |
  A snap package for modified realsense ros drivers packaged as an isolated snap mainly based on ros wrapper v2.0.3 and librealsense 2.10.3.
grade: stable
confinement: devmode

type: app

apps:
  ros-realsense-d400:
    command: rosrun ros_realsense_d400_snap_pkg rs_camera_snap.sh
    plugs: [network, network-bind, raw-usb]

  roscore:
    command: roscore
    plugs: [network, network-bind]

parts:
  workspace:
    plugin: catkin
    source-space: src
    include-roscore: true
    rosdistro: kinetic
    catkin-ros-master-uri: http://localhost:11311
    catkin-packages: [librealsense2, realsense2_camera, ros_realsense_d400_snap_pkg] 
